using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Qa6185.Permissions;
using Qa6185.MyEntities;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Qa6185.Shared;

namespace Qa6185.MyEntities
{
    public class MyEntitiesAppService : MyEntitiesAppServiceBase, IMyEntitiesAppService
    {
        //<suite-custom-code-autogenerated>
        public MyEntitiesAppService(IMyEntityRepository myEntityRepository, MyEntityManager myEntityManager, IDistributedCache<MyEntityExcelDownloadTokenCacheItem, string> excelDownloadTokenCache)
            : base(myEntityRepository, myEntityManager, excelDownloadTokenCache)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}