version: '3.7'

services:
  qa6185-web:
    image: mycompanyname/qa6185-web:latest
    container_name: qa6185-web
    hostname: qa6185-web
    build:
      context: ../../
      dockerfile: src/Qa6185.Web/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=5d6f06fe-5d51-4d70-b85c-17bf95c98167
      - App__SelfUrl=https://localhost:44353
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__Authority=http://qa6185-web
      - App__HealthCheckUrl=http://qa6185-web/health-status      
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Qa6185;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
    ports:
      - "44353:443"
    restart: on-failure
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network

  

  
  db-migrator:
    image: mycompanyname/qa6185-db-migrator:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: src/Qa6185.DbMigrator/Dockerfile.local
    environment:
      - OpenIddict__Applications__Qa6185_Web__RootUrl=https://localhost:44353
      - ConnectionStrings__Default=Data Source=sql-server;Initial Catalog=Qa6185;User Id=sa;Password=myPassw0rd;MultipleActiveResultSets=true;TrustServerCertificate=True;
      - Redis__Configuration=redis
    depends_on:
      sql-server:
        condition: service_healthy
    networks:
      - abp-network
  
  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1434:1433"
    environment:
      SA_PASSWORD: "myPassw0rd"
      ACCEPT_EULA: "Y"
    volumes:
      - sqldata:/var/opt/mssql
    networks:
      - abp-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S sql-server -U sa -P "myPassw0rd" -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
volumes:
  sqldata:
    name: qa6185_sqldata
networks:
  abp-network:
    name: qa6185-network
    driver: bridge