using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Qa6185.MyEntities
{
    public class MyEntity : MyEntityBase
    {
        //<suite-custom-code-autogenerated>
        protected MyEntity()
        {

        }

        public MyEntity(Guid id, string? name = null, string? property2 = null)
            : base(id, name, property2)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}