using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Qa6185.MyEntities
{
    public class MyEntityManager : MyEntityManagerBase
    {
        //<suite-custom-code-autogenerated>
        public MyEntityManager(IMyEntityRepository myEntityRepository)
            : base(myEntityRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}